### ISSUE TITLE
Race Condition when Resolving Proxies (Registering Stores)

### ISSUE THREAD

**Issue by AK2000** [proxystore/proxystore#319]
### Describe the problem.

I am resolving proxies in a threadpool, and I occasionally get this error:
`File "/pscratch/sd/a/alokvk2/proxystore/proxystore/store/base.py", line 96, in __call__
    obj = self.resolve()
  File "/pscratch/sd/a/alokvk2/proxystore/proxystore/store/base.py", line 134, in resolve
    store = self.get_store()
  File "/pscratch/sd/a/alokvk2/proxystore/proxystore/store/base.py", line 123, in get_store
    proxystore.store.register_store(store)
  File "/pscratch/sd/a/alokvk2/proxystore/proxystore/store/__init__.py", line 71, in register_store
    raise StoreExistsError(f'A store named {store.name} already exists.')`
I think this is caused by a race condition when resolving the proxies. If there are two proxies being resolved in different threads, both execute: 
[`store = proxystore.store.get_store(self.store_config['name'])`](https://github.com/proxystore/proxystore/blob/9a93f6d8c4ca44fde57cc43236fa592c8091ef65/proxystore/store/base.py#L136)
and both return None, so both of them try to register a store. I think this could be fixed either with a lock around this section of the code, or with a retry mechanism around the store creation that catches the StoreExistsError.

The bug is hard to reproduce consistently. It only happens to me on Perlmutter. However, I think resolving two proxies asynchronously could do the trick. I can work on creating a minimal example to reproduce the error.

### How did you install ProxyStore?

```console
From source
```

### ProxyStore Version

83920e9d135785c60b8a71a92e6ce0d4de1b90c0

### Python Version

3.10

### OS and Platform

x86 Linux

**Comment by gpauloski** [comment]
Thanks, @AK2000. This does seem like it needs a lock.

A naive solution would be to pass `exist_ok=True` to `get_store()` so the error isn't raised, but that would still possibly result in multiple stores being instantiated unnecessarily.

I think the change is fairly straightforward:
```diff
+ import threading

  _default_pool = ThreadPoolExecutor()
+ _factory_get_store_lock = threading.Lock()
```

```diff
+       with _factory_get_store_lock:
+           store = proxystore.store.get_store(self.store_config['name'])
+           if store is None:
+               store = Store.from_config(self.store_config)
+               proxystore.store.register_store(store)
+           return store
```
I'm pretty sure we want both `get_store` and `register_store` in the same lock.

Are you interested in submitting a PR for this?

**Comment by AK2000** [comment]
Hmm, I don't know why, but the lock doesn't seem to consistently fix the issue. I still occasionally get the same error. Is there any other place you can think of that could cause this condition?

**Comment by gpauloski** [comment]
Not that I'm aware of. We might need to create a reproducer then. Something along the lines of (1) create a proxy (without registering a store), (2) spawn a lot of threads, (3) resolve the proxy in each of the threads. It might not be totally deterministic but with enough threads it may be good enough for further debugging.

**Comment by gpauloski** [comment]
Another random thought---is for the proxying of Python modules?

If so, could it be that the `_factory_get_store_lock` is not actually shared across all threads? I'm wildly speculating here because I'm not sure of the actual mechanisms, but if each proxy across multiple threads is creating it's own version of the `proxystore.store.base` module and then putting that in `sys.modules`, it could be the case each thread has it's own lock.

**Comment by AK2000** [comment]
Haha, I think it was an issue with setup not with the solution. Turns out I had two versions of proxystore installed and it was not using the updated version. I think the lock should be sufficient. I haven't run pre-commit or the other tests yet which is why the PR is still marked as a draft.
