### ISSUE TITLE
Generate keys based on object hash

### ISSUE THREAD

**Issue by gpauloski** [proxystore/proxystore#4]
Currently, if the key associated with an object in the backend store is not specified, a random 128 bit string is generated as the key. A side effect of this is that if `to_proxy(obj, key=None)` is called twice, `obj` gets put into the backend twice. Having a means of generating a key based on the hash of `obj` would prevent the duplication.

`hash(obj)` could work however it may run into the same issues as using `id(obj)` as the key (return values from identical functions run on different nodes somewhat often have the same virtual address and therefore same id).

`hash(obj) + hash(str(obj))` could work better but we still have to design a means of dealing with hash collisions.

The current approach in the code is if you are doing to call `to_proxy()` twice, specify the key yourself to prevent the duplication.

**Comment by gpauloski** [comment]
To get an idea of the performance implications of switching from generating random byte strings (as we do now) to hashes, I ran the following script.

```Python
import hashlib
import os
import time

from proxystore.utils import create_key


for size in [1e1, 1e2, 1e3, 1e4, 1e5, 1e6, 1e7, 1e8, 1e9]:
    print(f'Data size: {size} bytes')

    times = []
    for _ in range(20):
        d = os.urandom(int(size))
        start = time.perf_counter_ns()
        # hashlib.md5(d)
        hash(d)
        times.append(time.perf_counter_ns() - start)

    avg_time = (sum(times) / len(times))
    print(f'hash time: {avg_time:.3f} ns')


times = []
for _ in range(20):
    start = time.perf_counter_ns()
    create_key(None)
    times.append(time.perf_counter_ns() - start)

avg_time = (sum(times) / len(times))
print(f'Average create_key() time: {avg_time:.3f} ns')
```

Which results in:
```
Data size: 10.0 bytes
hash time: 995.000 ns
Data size: 100.0 bytes
hash time: 985.000 ns
Data size: 1000.0 bytes
hash time: 1255.000 ns
Data size: 10000.0 bytes
hash time: 3960.000 ns
Data size: 100000.0 bytes
hash time: 31680.000 ns
Data size: 1000000.0 bytes
hash time: 317120.000 ns
Data size: 10000000.0 bytes
hash time: 3032285.000 ns
Data size: 100000000.0 bytes
hash time: 30231970.000 ns
Data size: 1000000000.0 bytes
hash time: 328675725.000 ns
Average create_key() time: 1875.000 ns
```

Our baseline is 1875 ns for generating random byte strings to moving to hashes becomes slower for anything over ~1KB. (Also this is with Python's builtin hash which is 64 bits usually so MD5 is even slower.) The time for ~1MB also seems acceptable, but 100MB+ can get pretty slow. We could potentially have some threshold for when we use hashes.

**Comment by gpauloski** [comment]
Also, `hash` is not usable because hash values for strings and bytes are salted with the salt value being randomly generated per process, so we will need to use MD5.

https://docs.python.org/3/reference/datamodel.html#object.__hash__

**Comment by gpauloski** [comment]
One issue with deduplication is a pattern like this:
```
p1 = store.proxy(myobj, evict=True)
p2 = store.proxy(myobj)

# One copy of myobj in the store because we hashed myobj

resolve(p1)
resolve(p2)  # raises resolve error because p1 evict myobj already
```

Maybe we need a way to mark objects in the store as "evictable" so event if `evict=True` for a single proxy, we can prevent it from evicting if another proxy was created with `evict=False`.

**Comment by ValHayot** [comment]
Yeah, I think you can just add a counter to each proxy object. Every time a proxy is created, +1 the counter. Every time the proxy is resolved and `evict=True`, -1 the counter. When `counter==0` evict.
I'm assuming this would be easy for the endpoints (could be wrong), but would maybe be problematic for the intra-site peers as it would require some form of locking. I think for the intra-site peers, it's OK to maintain duplicates as the memory available should scale with the number of nodes and the greater limitation is speed.

**Comment by gpauloski** [comment]
After #192, key generation will be unique to the `Connector` so I think it makes sense for individual `Connector`s to make the decision if this optimization is useful and how to implement it best with respect to reference counting.
