### ISSUE TITLE
Obfuscate keys from the user

### ISSUE THREAD

**Issue by gpauloski** [proxystore/proxystore#48]
### Describe the Request

ProxyStore is moving towards a write-once, read-many design philosophy which makes some existing functionality no longer needed. Specifically:
- User specified keys (users should use the key ProxyStore generates).
- The `strict` flag (consistency is not a concern if objects are only written once).

### Proposed Changes

1. Remote `strict` flag and timestamp related things in `proxystore.store`.
   - Also remove: https://github.com/gpauloski/proxystore/blob/a72e262f5a470641bc2a462569963440e30fd2ff/proxystore/store/file.py#L100
3. Remove specifying a key as an argument to `set()` and `proxy()`. `set()` will still return a key (just one the ProxyStore creates) and the proxy returned by `proxy()` will still contain the key.
4. [Optional] Implement #4 so we can check if an object is already stored and avoid duplicate work.

Notes:
- this also sets us up for the changes discussed in #49 where we move towards *better keys*. I.e., keys that are dataclasses and store additional metadata about objects.
- we may need to allow `set_bytes` to modify keys and return them to `set`. For example, in `GlobusStore` where we encode the Globus transfer task ID in the key.
- as noted in #82, removing the `key` param from `proxy/proxy_batch` should fix issues where `mypy` cannot determine the resulting proxy type, but this needs to be tested along with these changes.

**Comment by gpauloski** [comment]
@WardLT do you have any concerns about this proposal impacting how you use ProxyStore?

**Comment by WardLT** [comment]
Sounds great! I do have one application where I replace objects in the proxy store, which uses `batch_proxy` (so we should be sure that operation runs keys). I'll also to change that application to evict the old copy. 

Maybe some kind of "replace" operation would be useful - even if it's just a thin wrapper over "evict" and then "set"
